credentialConfigurations = {
  "MyUniCredential_jwt_vc_json" = {
    format = "jwt_vc_json"
    scope = "MyUniCredential_jwt_vc_json"
    cryptographic_binding_methods_supported = ["jwk", "did:key", "did:web"]
    credential_signing_alg_values_supported = ["ES256"]
    proof_types_supported = {
      jwt = {
        proof_signing_alg_values_supported = ["ES256", "EdDSA"]
      }
    }
    credential_definition = {
      type = ["VerifiableCredential", "MyUniCredential"]
    }
  }
}
