profiles {
  myUniCredential = {
    name = "My Uni Credential"
    credentialConfigurationId = "MyUniCredential_jwt_vc_json"
    issuerKey = ${defaultIssuerKey}
    issuerDid = ${defaultIssuerDid}
    credentialData = {
      "@context" = [
        "https://www.w3.org/2018/credentials/v1"
      ]
      type = ["VerifiableCredential", "MyUniCredential"]
      credentialSubject = {
        uniName = "My Uni"
        school = {
          name = "School of Computer Science"
        }
        studentInfo = {
          firstName = "James"
          lastName = "Smith"
          birthday = "2000-01-01T00:00:00Z"
          gender = "Male"
          intake = 2021
          school = "School of Computer Science"
          program = "Software Engineering"
          status = "Studying"
        }
        studentScore = {
          grade = "A"
          gpa = 4.0
          descriptor = "Excellent"
        }
      }
    }
    mapping = {
      id = "<uuid>"
      issuer = { id = "<issuerDid>" }
      credentialSubject = { id = "<subjectDid>" }
      issuanceDate = "<timestamp>"
      expirationDate = "<timestamp-in:365d>"
    }
  }
}
