services:
    issuer-api2:
        image: ${IMAGE_PREFIX}waltid/issuer-api2:${VERSION_TAG:-latest}
        profiles:
            - services
            - identity
            - all
        pull_policy: missing
        depends_on:
            - caddy
        env_file:
            - .env
        extra_hosts:
            - "$SERVICE_HOST:host-gateway"
        volumes:
            - ./issuer-api2/config:/waltid-issuer-api2/config

    verifier-api2:
        image: ${IMAGE_PREFIX}waltid/verifier-api2:${VERSION_TAG:-latest}
        profiles:
            - services
            - identity
            - all
        pull_policy: missing
        depends_on:
            - caddy
        env_file:
            - .env
        extra_hosts:
            - "$SERVICE_HOST:host-gateway"
        volumes:
            - ./verifier-api2/config:/waltid-verifier-api2/config

    wallet-api2:
        image: ${IMAGE_PREFIX}waltid/wallet-api2:${VERSION_TAG:-latest}
        profiles:
            - services
            - identity
            - all
        pull_policy: missing
        depends_on:
            postgres:
                condition: service_healthy
            caddy:
                condition: service_started
        env_file:
            - .env
        extra_hosts:
            - "$SERVICE_HOST:host-gateway"
        volumes:
            - ./wallet-api2/config:/waltid-wallet-api2/config

    postgres:
        image: docker.io/library/postgres:latest
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-U", "$DB_USERNAME"]
            interval: 5s
            timeout: 1s
            retries: 5
        restart: always
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - wallet-api-db:/waltid-wallet-api/data
        ports:
            - $POSTGRES_DB_PORT:5432 #TODO: tcp/udp proxy with caddy

    caddy:
        image: docker.io/caddy:2
        restart: unless-stopped
        env_file:
            - .env
        cap_add:
            - NET_ADMIN
        ports:
            - target: "$WALLET_BACKEND_PORT"
              published: $WALLET_BACKEND_PORT # wallet-api
              protocol: tcp
              mode: host

            - target: "$ISSUER_API_PORT"
              published: $ISSUER_API_PORT # issuer-api
              protocol: tcp
              mode: host

            - target: "$ISSUER_API2_PORT"
              published: $ISSUER_API2_PORT # issuer-api2
              protocol: tcp
              mode: host

            - target: "$VERIFIER_API_PORT"
              published: $VERIFIER_API_PORT # verifier-api
              protocol: tcp
              mode: host

            - target: "$VERIFIER_API2_PORT"
              published: $VERIFIER_API2_PORT # verifier-api2
              protocol: tcp
              mode: host

            - target: "$WALLET_API2_PORT"
              published: $WALLET_API2_PORT # wallet-api2
              protocol: tcp
              mode: host

            - target: "$DEMO_WALLET_FRONTEND_PORT"
              published: $DEMO_WALLET_FRONTEND_PORT # waltid-demo-wallet
              protocol: tcp
              mode: host

            - target: "$DEV_WALLET_FRONTEND_PORT"
              published: $DEV_WALLET_FRONTEND_PORT # waltid-dev-wallet
              protocol: tcp
              mode: host

            - target: "$WEB_PORTAL_PORT"
              published: $WEB_PORTAL_PORT # web-portal
              protocol: tcp
              mode: host

            - target: "$WEB_PORTAL2_PORT"
              published: $WEB_PORTAL2_PORT # web-portal2
              protocol: tcp
              mode: host

            - target: "$VC_REPO_PORT"
              published: $VC_REPO_PORT # vc-repo
              protocol: tcp
              mode: host

            - target: "$PG_ADMIN_PORT"
              published: $PG_ADMIN_PORT # pg-admin
              protocol: tcp
              mode: host

        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
volumes:
    wallet-api-db:
    vault_data:
    valkey_data:
